"""PostgreSQL persistence backend for conversations and citations."""

from __future__ import annotations

import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Iterable, Iterator

from psycopg import Connection
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool


_pools: dict[str, ConnectionPool] = {}


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _pool(database_url: str) -> ConnectionPool:
    pool = _pools.get(database_url)
    if pool is None:
        pool = ConnectionPool(
            conninfo=database_url,
            min_size=1,
            max_size=10,
            open=False,
            kwargs={"row_factory": dict_row},
        )
        pool.open(wait=True)
        _pools[database_url] = pool
    return pool


@contextmanager
def connection(database_url: str) -> Iterator[Connection]:
    """Yield a pooled transaction-scoped PostgreSQL connection."""
    with _pool(database_url).connection() as conn:
        yield conn


def close_pools() -> None:
    """Close all pools, primarily for tests and graceful process shutdown."""
    for pool in _pools.values():
        pool.close()
    _pools.clear()


def init_database(database_url: str) -> None:
    with connection(database_url) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS conversations (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id TEXT PRIMARY KEY,
                conversation_id TEXT NOT NULL
                    REFERENCES conversations(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS citations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_id TEXT NOT NULL
                    REFERENCES messages(id) ON DELETE CASCADE,
                source TEXT NOT NULL,
                page INTEGER NOT NULL,
                chunk_text TEXT NOT NULL,
                score DOUBLE PRECISION
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS image_citations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_id TEXT NOT NULL
                    REFERENCES messages(id) ON DELETE CASCADE,
                image_path TEXT NOT NULL,
                source TEXT NOT NULL,
                page INTEGER NOT NULL,
                score DOUBLE PRECISION
            )
            """
        )
        conn.execute(
            """CREATE INDEX IF NOT EXISTS idx_messages_conversation
            ON messages(conversation_id, created_at)"""
        )
        conn.execute(
            """CREATE INDEX IF NOT EXISTS idx_citations_message
            ON citations(message_id)"""
        )
        conn.execute(
            """CREATE INDEX IF NOT EXISTS idx_image_citations_message
            ON image_citations(message_id)"""
        )


def create_conversation(database_url: str, title: str = "新会话") -> str:
    conversation_id = str(uuid.uuid4())
    timestamp = _now()
    with connection(database_url) as conn:
        conn.execute(
            """INSERT INTO conversations (id, title, created_at, updated_at)
            VALUES (%s, %s, %s, %s)""",
            (conversation_id, title.strip() or "新会话", timestamp, timestamp),
        )
    return conversation_id


def list_conversations(database_url: str) -> list[dict]:
    with connection(database_url) as conn:
        rows = conn.execute(
            """SELECT id, title, created_at, updated_at
            FROM conversations ORDER BY updated_at DESC"""
        ).fetchall()
    return list(rows)


def get_conversation(database_url: str, conversation_id: str) -> dict | None:
    with connection(database_url) as conn:
        row = conn.execute(
            """SELECT id, title, created_at, updated_at
            FROM conversations WHERE id = %s""",
            (conversation_id,),
        ).fetchone()
    return row


def rename_conversation(database_url: str, conversation_id: str, title: str) -> None:
    clean_title = title.strip()
    if not clean_title:
        raise ValueError("Conversation title cannot be empty")
    with connection(database_url) as conn:
        conn.execute(
            """UPDATE conversations SET title = %s, updated_at = %s
            WHERE id = %s""",
            (clean_title, _now(), conversation_id),
        )


def delete_conversation(database_url: str, conversation_id: str) -> None:
    with connection(database_url) as conn:
        conn.execute("DELETE FROM conversations WHERE id = %s", (conversation_id,))


def add_message(
    database_url: str,
    conversation_id: str,
    role: str,
    content: str,
) -> str:
    if role not in {"user", "assistant"}:
        raise ValueError("role must be 'user' or 'assistant'")

    message_id = str(uuid.uuid4())
    timestamp = _now()
    with connection(database_url) as conn:
        conn.execute(
            """INSERT INTO messages
            (id, conversation_id, role, content, created_at)
            VALUES (%s, %s, %s, %s, %s)""",
            (message_id, conversation_id, role, content, timestamp),
        )
        conn.execute(
            "UPDATE conversations SET updated_at = %s WHERE id = %s",
            (timestamp, conversation_id),
        )
    return message_id


def get_messages(
    database_url: str,
    conversation_id: str,
    limit: int | None = None,
) -> list[dict]:
    with connection(database_url) as conn:
        if limit is None:
            rows = conn.execute(
                """SELECT id, conversation_id, role, content, created_at
                FROM messages WHERE conversation_id = %s
                ORDER BY created_at ASC""",
                (conversation_id,),
            ).fetchall()
        else:
            rows = conn.execute(
                """SELECT * FROM (
                    SELECT id, conversation_id, role, content, created_at
                    FROM messages WHERE conversation_id = %s
                    ORDER BY created_at DESC LIMIT %s
                ) recent ORDER BY created_at ASC""",
                (conversation_id, max(limit, 0)),
            ).fetchall()
    return list(rows)


def add_citations(
    database_url: str,
    message_id: str,
    citations: Iterable[dict],
) -> None:
    values = [
        (
            message_id,
            citation["source"],
            int(citation["page"]),
            citation.get("chunk_text", citation.get("text", "")),
            citation.get("score"),
        )
        for citation in citations
    ]
    if not values:
        return
    with connection(database_url) as conn:
        with conn.cursor() as cursor:
            cursor.executemany(
                """INSERT INTO citations
                (message_id, source, page, chunk_text, score)
                VALUES (%s, %s, %s, %s, %s)""",
                values,
            )


def get_citations(database_url: str, message_id: str) -> list[dict]:
    with connection(database_url) as conn:
        rows = conn.execute(
            """SELECT id, message_id, source, page, chunk_text, score
            FROM citations WHERE message_id = %s ORDER BY id ASC""",
            (message_id,),
        ).fetchall()
    return list(rows)


def add_image_citations(
    database_url: str,
    message_id: str,
    citations: Iterable[dict],
) -> None:
    values = [
        (
            message_id,
            citation["image_path"],
            citation["source"],
            int(citation["page"]),
            citation.get("score"),
        )
        for citation in citations
    ]
    if not values:
        return
    with connection(database_url) as conn:
        with conn.cursor() as cursor:
            cursor.executemany(
                """INSERT INTO image_citations
                (message_id, image_path, source, page, score)
                VALUES (%s, %s, %s, %s, %s)""",
                values,
            )


def get_image_citations(database_url: str, message_id: str) -> list[dict]:
    with connection(database_url) as conn:
        rows = conn.execute(
            """SELECT id, message_id, image_path, source, page, score
            FROM image_citations WHERE message_id = %s ORDER BY id ASC""",
            (message_id,),
        ).fetchall()
    return list(rows)
